AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false  # rubocop-capybara 등 추천 메시지 비활성화

  # 除外するディレクトリ（自動生成されるファイル）
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/*"
    - "node_modules/**/*"

plugins:
  - rubocop-rails

# 1行あたりの文字数をチェックする
Layout/LineLength:
  Max: 130
  Exclude:
    - "Rakefile"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

Layout/EndOfLine:
  Enabled: false

# RSpecのブロック内の行数チェックを除外
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 8

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 30

Metrics/BlockNesting:
  Max: 5

Metrics/ClassLength:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ClassAndModuleChildren:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# メソッドパラメータ名の最小文字数を設定
Naming/MethodParameterName:
  MinNameLength: 1
  AllowedNames: [x, y, i, j, k] # 루프 변수 허용
